# Autogenerated wrapper script for rocSOLVER_jll for x86_64-linux-musl-cxx11
export librocsolver

using ROCmCompilerSupport_jll
using ROCmOpenCLRuntime_jll
using ROCmDeviceLibs_jll
using rocminfo_jll
using hsa_rocr_jll
using HIP_jll
using rocBLAS_jll
JLLWrappers.@generate_wrapper_header("rocSOLVER")
JLLWrappers.@declare_library_product(librocsolver, "librocsolver.so.0")
function __init__()
    JLLWrappers.@generate_init_header(ROCmCompilerSupport_jll, ROCmOpenCLRuntime_jll, ROCmDeviceLibs_jll, rocminfo_jll, hsa_rocr_jll, HIP_jll, rocBLAS_jll)
    JLLWrappers.@init_library_product(
        librocsolver,
        "rocsolver/lib/librocsolver.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
